# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon
import ctypes
ctypes.windll.shell32.SetCurrentProcessExplicitAppUserModelID("myappid")


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1060, 600)
        MainWindow.setStyleSheet("background-color:rgb(0, 255, 255)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(200)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setStyleSheet("background-color:rgb(137, 78, 84);\n"
"border-radius:10px;\n"
"color:rgb(255, 255, 255);\n"
"font-family:\'Roman, 华文行楷\';\n"
"font-size:16pt")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setStyleSheet("background-color:rgb(137, 78, 84);\n"
"border-radius:10px;\n"
"color:rgb(255, 255, 255);\n"
"font-family:\'Roman, 华文行楷\';\n"
"font-size:16pt")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.label_2.setStyleSheet("background-color:rgb(137, 78, 84);\n"
"border-radius:10px;\n"
"color:rgb(255, 255, 255);\n"
"font-family:\'Roman, 华文行楷\';\n"
"font-size:16pt")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(50)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.objectView = QtWidgets.QGraphicsView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.objectView.sizePolicy().hasHeightForWidth())
        self.objectView.setSizePolicy(sizePolicy)
        self.objectView.setStyleSheet("background-color:rgb(122, 115, 116)")
        self.objectView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.objectView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.objectView.setObjectName("objectView")
        self.horizontalLayout_2.addWidget(self.objectView)
        self.srcImageView = QtWidgets.QGraphicsView(self.centralwidget)
        self.srcImageView.setStyleSheet("background-color:rgb(122, 115, 116)")
        self.srcImageView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.srcImageView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.srcImageView.setObjectName("srcImageView")
        self.horizontalLayout_2.addWidget(self.srcImageView)
        self.interpretView = QtWidgets.QGraphicsView(self.centralwidget)
        self.interpretView.setStyleSheet("background-color:rgb(122, 115, 116)")
        self.interpretView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.interpretView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.interpretView.setObjectName("interpretView")
        self.horizontalLayout_2.addWidget(self.interpretView)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 15)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(150)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_3.addWidget(self.pushButton_2)
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_3.addWidget(self.pushButton_4)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_3.addWidget(self.pushButton)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_3.addWidget(self.pushButton_3)
        self.gridLayout.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1060, 30))
        self.menubar.setStyleSheet("background:rgb(137, 73, 84);\n"
"color:rgb(255, 255, 255);\n"
"font-family:\'Roman, 华文行楷\';\n"
"font-size:12pt")
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.menu.setAutoFillBackground(False)
        self.menu.setStyleSheet("background-color:rgb(137, 73, 84);\n"
"border-radius:10px;")
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setStyleSheet("")
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionopenfile = QtWidgets.QAction(MainWindow)
        self.actionopenfile.setObjectName("actionopenfile")
        self.action_whitespace = QtWidgets.QAction(MainWindow)
        self.action_whitespace.setObjectName("action_whitespace")
        self.actionYour_suggestions = QtWidgets.QAction(MainWindow)
        self.actionYour_suggestions.setObjectName("actionYour_suggestions")
        self.menu.addAction(self.actionopenfile)
        self.menu_2.addAction(self.action_whitespace)
        self.menu_3.addAction(self.actionYour_suggestions)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "文物图片"))
        self.label_3.setText(_translate("MainWindow", "拓片图像"))
        self.label_2.setText(_translate("MainWindow", "对应释文"))
        self.pushButton_2.setText(_translate("MainWindow", "了解器物"))
        self.pushButton_4.setText(_translate("MainWindow", "查看原始拓片"))
        self.pushButton.setText(_translate("MainWindow", "了解原文"))
        self.pushButton_3.setText(_translate("MainWindow", "了解释文"))
        self.menu.setTitle(_translate("MainWindow", "导入图片"))
        self.menu_2.setTitle(_translate("MainWindow", "                                                                                                    "))
        self.menu_3.setTitle(_translate("MainWindow", "用户反馈"))
        self.actionopenfile.setText(_translate("MainWindow", "openfile"))
        self.action_whitespace.setText(_translate("MainWindow", " "))
        self.actionYour_suggestions.setText(_translate("MainWindow", "Your suggestions"))
        self.pushButton_2.clicked.connect(self.popWindow1)
        self.pushButton.clicked.connect(self.popWindow2)
        self.pushButton_3.clicked.connect(self.popWindow3)
        self.pushButton_4.clicked.connect(self.popsrc)
        self.setWindowIcon(QIcon('logo.png'))
