# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'srcWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_srcForm(object):
    def setupUi(self, srcForm):
        srcForm.setObjectName("srcForm")
        srcForm.resize(400, 377)
        self.gridLayout = QtWidgets.QGridLayout(srcForm)
        self.gridLayout.setObjectName("gridLayout")
        self.src = QtWidgets.QGraphicsView(srcForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.src.sizePolicy().hasHeightForWidth())
        self.src.setSizePolicy(sizePolicy)
        self.src.setStyleSheet("background-color:rgb(122, 115, 116)")
        self.src.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.src.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.src.setObjectName("src")
        self.gridLayout.addWidget(self.src, 0, 0, 1, 1)

        self.retranslateUi(srcForm)
        QtCore.QMetaObject.connectSlotsByName(srcForm)

    def retranslateUi(self, srcForm):
        _translate = QtCore.QCoreApplication.translate
        srcForm.setWindowTitle(_translate("srcForm", "Form"))
