# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'suggestions.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Suggestions(object):
    def setupUi(self, Suggestions):
        Suggestions.setObjectName("Suggestions")
        Suggestions.resize(400, 300)
        self.gridLayout = QtWidgets.QGridLayout(Suggestions)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton = QtWidgets.QPushButton(Suggestions)
        self.pushButton.setStyleSheet("background-color:rgb(137, 78, 84);\n"
"border-radius:10px;\n"
"color:rgb(255, 255, 255);\n"
"font-family:\'Roman, 华文行楷\';\n"
"font-size:16pt")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(Suggestions)
        self.label.setStyleSheet("background-color:rgb(137, 78, 84);\n"
"border-radius:10px;\n"
"color:rgb(255, 255, 255);\n"
"font-family:\'Roman, 华文行楷\';\n"
"font-size:16pt")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(Suggestions)
        self.plainTextEdit.setStyleSheet("background-color:rgb(122, 115, 116);\n"
"color:rgb(255, 255, 255);\n"
"font-family:\'Roman, 华文行楷\';\n"
"font-size:16pt")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.gridLayout.addWidget(self.plainTextEdit, 1, 0, 1, 1)

        self.retranslateUi(Suggestions)
        QtCore.QMetaObject.connectSlotsByName(Suggestions)

    def retranslateUi(self, Suggestions):
        _translate = QtCore.QCoreApplication.translate
        Suggestions.setWindowTitle(_translate("Suggestions", "Form"))
        self.pushButton.setText(_translate("Suggestions", "提交"))
        self.label.setText(_translate("Suggestions", "建议反馈栏"))
        self.pushButton.clicked.connect(self.submit)

    def submit(self):
        text = self.plainTextEdit.toPlainText()
        with open('suggestions.txt', mode='a') as file:
            file.write(text)
            file.write('\n')
        self.Message()

    def Message(self):
        self.mymessage = QtWidgets.QMessageBox()
        self.mymessage.setWindowTitle('提示')
        self.mymessage.setText('已提交！')
        self.mymessage.setStyleSheet("QPushButton:hover{background-color: rgb(255, 93, 52);}")
        self.mymessage.exec_()
